[package]
name = "penguin-rp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
env_logger = "0.11.5"
log = "0.4.22"
pingora = "0.4.0"
pingora-core = "0.4.0"
pingora-proxy = "0.4.0"
